import { SERVICES } from "./services";

export const DEFAULT_SERVICES = {

  STUDENT: [

    SERVICES.HOME,
    SERVICES.INBOX,
    SERVICES.TASKS,
    SERVICES.EVENTS,
    SERVICES.PROFILE,

  ],

  FACULTY: [

    SERVICES.HOME,
    SERVICES.GROUPS,
    SERVICES.SEND_MESSAGE,
    SERVICES.MESSAGE_ANALYTICS,
    SERVICES.TASKS,
    SERVICES.TASK_DASHBOARD,
    SERVICES.EVENTS,
    SERVICES.PROFILE,

  ],

  SUPER_ADMIN: [

    SERVICES.HOME,

    SERVICES.USER_MANAGEMENT,

    SERVICES.GROUP_MANAGEMENT,

    SERVICES.CATEGORY_MANAGEMENT,

    SERVICES.INSTITUTE_MANAGEMENT,

    SERVICES.DEPARTMENT_MANAGEMENT,

    SERVICES.ROLE_MANAGEMENT,

    SERVICES.REPORTS,

    SERVICES.PROFILE,

  ],

};