export const SERVICES = {
  HOME: "HOME",

  GROUPS: "GROUPS",

  SEND_MESSAGE: "SEND_MESSAGE",

  MESSAGE_ANALYTICS: "MESSAGE_ANALYTICS",

  TASKS: "TASKS",

  TASK_DASHBOARD: "TASK_DASHBOARD",

  EVENTS: "EVENTS",

  INBOX: "INBOX",

  PROFILE: "PROFILE",

  USER_MANAGEMENT: "USER_MANAGEMENT",

  GROUP_MANAGEMENT: "GROUP_MANAGEMENT",

  CATEGORY_MANAGEMENT: "CATEGORY_MANAGEMENT",

  INSTITUTE_MANAGEMENT: "INSTITUTE_MANAGEMENT",

  DEPARTMENT_MANAGEMENT: "DEPARTMENT_MANAGEMENT",

  ROLE_MANAGEMENT: "ROLE_MANAGEMENT",

  REPORTS: "REPORTS",
} as const;